### ISSUE TITLE
Need some help trying to figure out the code

### ISSUE THREAD

**Issue by HRankit** [sbkwgh/forum#24]
https://github.com/sbkwgh/forum/blob/65b53e44cf9af6d5b702513baa55cefaec1cf90c/routes/post.js#L39

Can I know the location of Add Likes Function which is being called?

https://github.com/sbkwgh/forum/blob/65b53e44cf9af6d5b702513baa55cefaec1cf90c/routes/post.js#L53

Same way the location for remove likes?

I'm unable to figure out how the likes are being stored and fetched in the database. I couldn't find any column or table for this, hence the issue. 

I hope this functionality is still working in this.

I'd be grateful if you could help me clear the issue.

**Comment by sbkwgh** [comment]
Hi there - so it's a bit of a fudge because it's not really storing 'likes' per se. It's just using a join table to associate a set of users with a given post. In the model this is then given an alias as 'likes' (because that's what it semantically represents here)

https://github.com/sbkwgh/forum/blob/06a764cb4590ad6b1f605fb4d4fdad92676978ea/models/post.js#L82

which then means we get access to the methods `removeLikes` and `addLikes` thanks to sequelize.
